# main text of home
name: Wenjun Huang
bio: A Boy who wants more

# twitter summary info
description: A blog about technology and stuff related

picture: assets/images/hwj.jpg

url: https://hubery94.github.io/
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
github: hubery94
email:  2011huang@whu.edu.cn

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
